show databases;
Use customer_behavior;
 
 SHOW TABLES;
 desc customer;
 ALTER TABLE customer
CHANGE `Customer ID` customer_id BIGINT,
CHANGE `Age` age BIGINT,
CHANGE `Gender` gender TEXT,
CHANGE `Item Purchased` item_purchased TEXT,
CHANGE `Category` category TEXT,
CHANGE `Purchase Amount (USD)` purchase_amount_usd BIGINT,
CHANGE `Location` location TEXT,
CHANGE `Size` size TEXT,
CHANGE `Color` color TEXT,
CHANGE `Season` season TEXT,
CHANGE `Review Rating` review_rating DOUBLE,
CHANGE `Subscription Status` subscription_status TEXT,
CHANGE `Shipping Type` shipping_type TEXT,
CHANGE `Discount Applied` discount_applied TEXT,
CHANGE `Promo Code Used` promo_code_used TEXT,
CHANGE `Previous Purchases` previous_purchases BIGINT,
CHANGE `Payment Method` payment_method TEXT,
CHANGE `Frequency of Purchases` frequency_of_purchases TEXT;

 
 #1.what is the total revenue generated by male vs female customers?
 
 SELECT gender,
		SUM(`purchase_amount_usd`) AS revenue
FROM customer
GROUP BY gender;

#2.which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,
           purchase_amount_usd
	FROM customer
	WHERE discount_applied = 'Yes'
	AND purchase_amount_usd >= (
		SELECT AVG(purchase_amount_usd)
		FROM customer
		);
        
#3.which are the top 5 products with the highest average review rating?

SELECT item_purchased,category,
ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased, category
ORDER BY avg_rating DESC
LIMIT 5;
 
#4.compare the average purchase amounts between standard and express shopping?

SELECT shipping_type,
ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

#5.Do subscribed customers spend more ?compare average spped and total revenue between subcribers and non subscribers?

SELECT subscription_status,
COUNT(*) AS customer_count,
ROUND(AVG(purchase_amount_usd), 2) AS avg_spend,
SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY subscription_status;

#6.which 5 products have the highest percentage of purchase with discounts applied?

SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0)/ COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
  
  #7.segment customers into new ,returning and loyal based on thier total number of previous purchases, and show the count of each segment?
  
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

 #8.what are the top 3 most purchased products with in each category?
 
 SELECT rn AS item_rank,
       category,
       item_purchased,
       purchase_count
FROM (
SELECT category,item_purchased,
COUNT(*) AS purchase_count,ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
FROM customer
GROUP BY category, item_purchased
) AS ranked_products
WHERE rn <= 3
ORDER BY category, item_rank;

#9.Are customers who are repeat BUYERS (MORE than 5 previous purchases) also likely to subscribe?

SELECT
ROW_NUMBER() OVER (ORDER BY subscription_status) AS sr_no,subscription_status,
COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#10.what is the revenue count contribution of each age group?

SELECT ROW_NUMBER() OVER () AS sr_no,age_group,total_revenue
FROM (
SELECT 
CASE WHEN age BETWEEN 18 AND 25 THEN 'Young Adult'
WHEN age BETWEEN 26 AND 35 THEN 'Middle Aged'
WHEN age BETWEEN 36 AND 45 THEN 'Adult'
ELSE 'Senior'
END AS age_group,
SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
) AS grouped_data
ORDER BY 
CASE age_group
WHEN 'Young Adult' THEN 1
WHEN 'Middle Aged' THEN 2
WHEN 'Adult' THEN 3
WHEN 'Senior' THEN 4
END;


  